In [1]:
'''
Steps:-
1: Type on google "Numpy Documentation"
2: Click on lates version
3: Click on API Reference

Numpy & Panda is used for input/processing type operations
Matplotlib us used for output
for processing - Sklearn, tensorflow, pytouch
'''

'\nSteps:-\n1: Type on google "Numpy Documentation"\n2: Click on lates version\n3: Click on API Reference\n\nNumpy & Panda is used for input/processing type operations\nMatplotlib us used for output\nfor processing - Sklearn, tensorflow, pytouch\n'

In [2]:
import numpy as np

numbers = np.array([1, 2, 3, 5, 7, 10])
print(type(numbers))
print(numbers.ndim)     #dimension of array
print(numbers.shape)    #no. of rows and columns
print(numbers)

<class 'numpy.ndarray'>
1
(6,)
[ 1  2  3  5  7 10]


In [3]:
num = np.array([[1, 2, 3], [5, 7, 10]])
print(type(num))
print(f"This is a {num.ndim}D Array.")     #dimension of array
print(num.shape)                           #no. of rows and columns
print(num)

<class 'numpy.ndarray'>
This is a 2D Array.
(2, 3)
[[ 1  2  3]
 [ 5  7 10]]


In [4]:
grades = np.array([[78, 82, 85], [81, 85, 87], [91, 89, 71]]) #one row is 1 student having marks of 3 subjects

print(grades.min())     #lowest marks in school
print(grades.max())     #highest in school
print(grades.mean())    #school avergae
print()
print(grades.min(axis = 0))     #min for each subject
print(grades.max(axis = 0))     #max for each subject
print(grades.mean(axis = 0))    #average for each subject
print()
print(grades.min(axis = 1))     #min for each student
print(grades.max(axis = 1))     #max for each student
print(grades.mean(axis = 1))    #average for each student

71
91
83.22222222222223

[78 82 71]
[91 89 87]
[83.33333333 85.33333333 81.        ]

[78 81 71]
[85 87 91]
[81.66666667 84.33333333 83.66666667]


In [5]:
grade = np.array([78, 82, 85, 73, 81, 85, 87, 91, 92, 91, 89, 71]) 
print("Before array: ", grade)
print("Shape of array: ", grade.shape, "\n")
grade = grade.reshape(2, 3, 2)
print("After array: ", grade)
print("Shape of array: ", grade.shape)

Before array:  [78 82 85 73 81 85 87 91 92 91 89 71]
Shape of array:  (12,) 

After array:  [[[78 82]
  [85 73]
  [81 85]]

 [[87 91]
  [92 91]
  [89 71]]]
Shape of array:  (2, 3, 2)


In [6]:
'''
Numpy Array Attributes:- 

ndarray.flags    : Information about the memory layout of the array.
ndarray.shape    : Tuple of array dimensions.
ndarray.strides  : Tuple of bytes to step in each dimension when traversing an array.
ndarray.ndim     : Number of array dimensions.
ndarray.data     : Python buffer object pointing to the start of the array's data.
ndarray.size     : Number of elements in the array.
ndarray.itemsize : Length of one array element in bytes.
ndarray.nbytes   : Total bytes consumed by the elements of the array.
ndarray.base     : Base object if memory is from some other object.
ndarray.dtype    : Data-type of the array's elements.
ndarray.T        : View of the transposed array.
ndarray.real     : The real part of the array.
ndarray.imag     : The imaginary part of the array.
ndarray.flat     : A 1-D iterator over the array.'''

"\nNumpy Array Attributes:- \n\nndarray.flags    : Information about the memory layout of the array.\nndarray.shape    : Tuple of array dimensions.\nndarray.strides  : Tuple of bytes to step in each dimension when traversing an array.\nndarray.ndim     : Number of array dimensions.\nndarray.data     : Python buffer object pointing to the start of the array's data.\nndarray.size     : Number of elements in the array.\nndarray.itemsize : Length of one array element in bytes.\nndarray.nbytes   : Total bytes consumed by the elements of the array.\nndarray.base     : Base object if memory is from some other object.\nndarray.dtype    : Data-type of the array's elements.\nndarray.T        : View of the transposed array.\nndarray.real     : The real part of the array.\nndarray.imag     : The imaginary part of the array.\nndarray.flat     : A 1-D iterator over the array."

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("ndarray.flags      :", arr.flags)
print("ndarray.shape      :", arr.shape)
print("ndarray.strides    :", arr.strides)
print("ndarray.ndim       :", arr.ndim)
print("ndarray.data       :", arr.data)
print("ndarray.size       :", arr.size)
print("ndarray.itemsize   :", arr.itemsize)
print("ndarray.nbytes     :", arr.nbytes)
print("ndarray.base       :", arr.base)
print("ndarray.dtype      :", arr.dtype)
print("ndarray.T          :", arr.T)
print("ndarray.real       :", arr.real)
print("ndarray.imag       :", arr.imag)
print("ndarray.flat       :", arr.flat)

ndarray.flags      :   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

ndarray.shape      : (2, 3)
ndarray.strides    : (24, 8)
ndarray.ndim       : 2
ndarray.data       : <memory at 0x75d6c61a8c70>
ndarray.size       : 6
ndarray.itemsize   : 8
ndarray.nbytes     : 48
ndarray.base       : None
ndarray.dtype      : int64
ndarray.T          : [[1 4]
 [2 5]
 [3 6]]
ndarray.real       : [[1 2 3]
 [4 5 6]]
ndarray.imag       : [[0 0 0]
 [0 0 0]]
ndarray.flat       : <numpy.flatiter object at 0x34bbf10>


In [8]:
a = np.zeros(5)
print(a, "\n")
# np.zeros(5) creates an array of 5 elements, all initialized to 0.
# The argument (5) specifies the size of the array.

b = np.ones((5, 2))
print(b, "\n")
# np.ones((5, 2)) creates a 5x2 array filled with ones.
# The argument (5, 2) specifies the shape of the array (5 rows, 2 columns).

c = np.full((3, 2), 12)
print(c, "\n")
# np.full((3, 2), 12) creates a 3x2 array where each element is initialized to the value 12.
# The first argument (3, 2) specifies the shape of the array.
# The second argument (12) is the value that fills the array.

d = np.arange(5)
print(d, "\n")
# np.arange(5) creates an array of evenly spaced values, starting from 0 up to (but not including) 5.
# The argument (5) specifies the endpoint (exclusive), and by default, the step size is 1.

e = np.linspace(2, 10 ,3) #(start, end, step)
print(e, "\n")
# np.linspace(2, 10, 3) creates an array of 3 evenly spaced values between 2 and 10 (inclusive).
# The first argument (2) specifies the starting point.
# The second argument (10) specifies the endpoint (inclusive).
# The third argument (3) specifies the number of values to generate,
#                                      which are evenly spaced between the start and end points.

[0. 0. 0. 0. 0.] 

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

[[12 12]
 [12 12]
 [12 12]] 

[0 1 2 3 4] 

[ 2.  6. 10.] 



In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# 1. Reshape to 3x2
arr_reshape1 = arr.reshape(3, 2)
print("Reshape to 3x2:\n", arr_reshape1)

# 2. Reshape to 6x1
arr_reshape2 = arr.reshape(6, 1)
print("\nReshape to 6x1:\n", arr_reshape2)

# 3. Reshape to 1x6
arr_reshape3 = arr.reshape(1, 6)
print("\nReshape to 1x6:\n", arr_reshape3)

# 4. Reshape to 2x3 (same as original)
arr_reshape4 = arr.reshape(2, 3)
print("\nReshape to 2x3 (same as original):\n", arr_reshape4)

# 5. Reshape using -1 for automatic dimension calculation (2 columns)
arr_reshape5 = arr.reshape(-1, 2)
print("\nReshape using -1 for automatic dimension (2 columns):\n", arr_reshape5)


Reshape to 3x2:
 [[1 2]
 [3 4]
 [5 6]]

Reshape to 6x1:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

Reshape to 1x6:
 [[1 2 3 4 5 6]]

Reshape to 2x3 (same as original):
 [[1 2 3]
 [4 5 6]]

Reshape using -1 for automatic dimension (2 columns):
 [[1 2]
 [3 4]
 [5 6]]


In [10]:
#WAP to multiply two 3x4 matrices using numpy functions

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
b = np.array([[16, 15, 14, 13], [12, 11, 10, 9], [8, 7, 6, 5], [4, 3, 2, 1]])
prod = np.dot(a, b)
print("matrix multiplication:\n", prod)

matrix multiplication:
 [[ 80  70  60  50]
 [240 214 188 162]
 [400 358 316 274]
 [560 502 444 386]]


In [14]:
#indexing & slicing:-

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [15]:
#print third row and second column element of a numpy 2D Array:

print(arr[2, 1])

10


In [21]:
#select and print a subset of 2d array using slicing

print("Subset:\n", arr[1:4, 1:4]) #arr[row index, column index]

Subset:
 [[ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [19]:
#print any one row or column of a 2D Array

print("One Row:\n", arr[2,:])
print("One Column:\n", arr[:,1])

One Row:
 [ 9 10 11 12]
One Column:
 [ 2  6 10 14]


In [23]:
ar = np.array([[1, 2, 3],[4, 5, 6]])

#numpy shallow copy (.view()) change 1 element of the 2nd dimension

ar1 = ar.view()
ar1[0][1] = 20
print(ar)
print()
print(ar1)

[[ 1 20  3]
 [ 4  5  6]]

[[ 1 20  3]
 [ 4  5  6]]


In [25]:
#numpy deep copy (.copy()) change 1 element of the 2nd dimension

ar2 = ar.copy()
ar2[0][1] = 25
print(ar)
print()
print(ar2)

[[ 1 20  3]
 [ 4  5  6]]

[[ 1 25  3]
 [ 4  5  6]]


In [30]:
#Transpose a 2D Array, Resize a 2D Array, Flatten a 2D Array & display it

ar = np.array([[1, 2, 3],[4, 5, 6]])
print(np.transpose(ar), "\n")    # or print(ar.T)
print(np.resize(ar, (3, 2)), "\n")
print(ar.flatten(), "\n")

[[1 4]
 [2 5]
 [3 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[1 2 3 4 5 6] 



In [36]:
#find the most frequent element of a numpy array (do not use statistics package)

ar = np.array([[1, 2], [1, 2], [2, 3, 4]])
ar = ar.flatten()
freq = np.bincount(a).argmax()
print(freq)



ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.